// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using NS.Bot.BuisnessLogic;

#nullable disable

namespace NS.Bot.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NS.Bot.Shared.Entities.GuildEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("NS.Bot.Shared.Entities.TicketEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("NS.Bot.Shared.Entities.TicketSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdminTicketsCount")
                        .HasColumnType("bigint");

                    b.Property<long>("CuratorTicketsCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("HelperTicketsCount")
                        .HasColumnType("bigint");

                    b.Property<decimal>("NewAdminTicketsCategoryId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("NewAdminTicketsChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("NewCuratorTicketsCategoryId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("NewCuratorTicketsChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("NewHelperTicketsCategoryId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("NewHelperTicketsChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("OldAdminTicketsCategory")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("OldCuratorTicketsCategory")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("OldHelperTicketsCategory")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("TicketLogs")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("TicketSettings");
                });

            modelBuilder.Entity("NS.Bot.Shared.Entities.TicketEntity", b =>
                {
                    b.HasOne("NS.Bot.Shared.Entities.GuildEntity", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("NS.Bot.Shared.Entities.TicketSettings", b =>
                {
                    b.HasOne("NS.Bot.Shared.Entities.GuildEntity", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId");

                    b.Navigation("Guild");
                });
#pragma warning restore 612, 618
        }
    }
}
